ofs:
    - settings:
        platform : n6001
        family : agilex
        fim : base_x16
        part : AGFB014R24A2E2V
        device_id : 6001
pcie:
    - settings:
        output_name : pcie_ss
      pf0:
        num_vfs : 3
        bar0_address_width : 20
        vf_bar0_address_width : 20
      pf1:
      pf2:
        bar0_address_width : 18
      pf3:
      pf4:

iopll:
    - settings:
        output_name : sys_pll
        instance_name : iopll_0
      p_clk:
        freq : 470
memory:
    - settings:
        output_name : mem_ss
        preset : n6001
hssi:
    - settings:
        output_name : hssi_ss
        num_channels : 8
        data_rate : 25GbE

